package com.linjun.yunjunrui.db;

import android.database.sqlite.SQLiteDatabase;

import com.linjun.yunjunrui.model.Usermodel;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig usermodelDaoConfig;

    private final UserModelDao usermodelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        usermodelDaoConfig = daoConfigMap.get(UserModelDao.class).clone();
        usermodelDaoConfig.initIdentityScope(type);

        usermodelDao = new UserModelDao(usermodelDaoConfig, this);

        registerDao(Usermodel.class, usermodelDao);
    }

    public void clear() {
        usermodelDaoConfig.getIdentityScope().clear();
    }

    public UserModelDao getUsermodelDao() {
        return usermodelDao;
    }

}
